### PR TITLE
fix(header): Mobile menu closes as expected

### LINKED ISSUE #41: [Bug] Mobile menu doesn't automatically close when link clicked
### Description of the Bug

On mobile, the menu doesn't automatically close when you tap on a link.

### Reproduction Steps

1. Open the home page on a mobile device (or make a desktop browser window width small).
2. Click on the menu button.
3. Click on a page link and notice that the page has changed, but the menu doesn't change.

### Expected Behaviour

The menu should automatically close when you tap on a link.

### OS

iOS

### Browser

Safari

### Device

_No response_

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by phoenixpereira**
### Description
Makes the mobile menu close as expected.

### Changes Made
- Fixes mobile menu remaining open on window resize
- Fixes mobile menu not automatically closing when the link is clicked

### Related Issues
Fixes #41 and #42. 

### Additional Notes
N/A

### CODE REVIEW

File: src/components/Header.tsx [hunk 1]
```diff
@@ -21,12 +21,24 @@ export default function Header() {
 
     useEffect(() => {
```
Comment (jsun969) [inline src/components/Header.tsx:22]: use `useMount` from `@/hooks/use-mount` instead of `useEffect`

another better suggestion is [A third party event listener hook](https://usehooks-ts.com/react-hook/use-event-listener) which optimise event listener in react. (It's ok for only use `useMount` if you don't want to install a third party hook lib)

**Review by jsun969 — CHANGES_REQUESTED** [review]

File: src/components/Header.tsx [hunk 2]
```diff
@@ -21,12 +21,24 @@ export default function Header() {
...
+            window.removeEventListener('resize', handleResize);
         };
     }, []);
 
+    const closeMenu = () => {
+        setIsMenuOpen(false);
+    };
+
+    const handleResize = () => {
+        if (window.innerWidth >= 768) {
```
Comment (rayokamoto) [inline src/components/Header.tsx:37]: It might be better to have a set of constants which define breakpoints under the `constants` folder or something

**Review by rayokamoto — CHANGES_REQUESTED** [review]

File: src/components/Header.tsx (hunk 1 above)
Comment (phoenixpereira) [reply src/components/Header.tsx:22]: I'll just use useMount for now.

File: src/components/Header.tsx (hunk 2 above)
Comment (phoenixpereira) [reply src/components/Header.tsx:37]: Should I do this for just md (768px), or should I include other sizes that Tailwind uses like lg (1024px)?

Comment (rayokamoto) [reply src/components/Header.tsx:37]: I'd say other sizes as well

**Review by jsun969 — APPROVED** [review]
LGTM

**Review by rayokamoto — APPROVED** [review]
