### PR TITLE
fix: Set timezone for end time and dynamically calculate event end

### LINKED ISSUE #177: [Bug] Fix time being UTC instead of ACST
### Description of the Bug

Event's don't end at the correct time due to the code basing the end time on UTC instead of ACST.

### Reproduction Steps

1. Go to the website after an event has ended (up to a few hours ago)
2. Notice that the event still shows up as upcoming rather than past.

### Expected Behaviour

The events should end at the correct time and use ACST.

### OS

macOS

### Browser

_No response_

### Device

_No response_

### Additional Notes

Server time must remain using UTC, so a code change is needed to fix this. Perhaps have a function to convert the `endDate` for each event from ACST to UTC.

### PR DESCRIPTION
**Pull request by shfc**
### Description
The event status doesn't update correctly from upcoming to past because the event dates were being parsed with the incorrect timezone (default UTC) and the event end time was calculated outside the component, preventing updates after the initial render.

### Changes Made
- Updated the `getEventDate` function to correctly parse and convert event dates to the ACST timezone using `luxon`.
- The event filtering logic is replaced inside the Events component, ensuring these values are recalculated on each render.
- Added a comment in events.ts to specify that all event times are in ACST.

### Related Issues
Fixes #177 

### Additional Notes
N/A

### CODE REVIEW

**Review by phoenixpereira — APPROVED** [review]

File: src/app/events/Events.tsx [hunk 1]
```diff
@@ -76,14 +77,19 @@ function EventCard({
...
 };
-const CURRENT_DATE = new Date();
-const UPCOMING_EVENTS = EVENTS.filter((event) => getEventDate(event) >= CURRENT_DATE);
-const PAST_EVENTS = EVENTS.filter((event) => getEventDate(event) < CURRENT_DATE).reverse(); // Most recent event first
+
 export default function Events({ className }: { className?: string }) {
+    const CURRENT_DATE = new Date();
+    const UPCOMING_EVENTS = EVENTS.filter((event) => getEventDate(event) >= CURRENT_DATE);
+    const PAST_EVENTS = EVENTS.filter((event) => getEventDate(event) < CURRENT_DATE).reverse(); // Most recent event first
+
```
Comment (jsun969) [inline src/app/events/Events.tsx:92]: define the variable inside a server component will cause it to be re-defined every time client request for this component.

Can we move these variables outside the component(function)?

**Review by jsun969 — CHANGES_REQUESTED** [review]

File: src/app/events/Events.tsx (hunk 1 above)
Comment (jsun969) [reply src/app/events/Events.tsx:92]: mb, it should be redefined

**Review by jsun969 — APPROVED** [review]
LGTM

**Review by rayokamoto — APPROVED** [review]
