### PR TITLE
fix: prevent events duplication by using React state

### LINKED ISSUE #295: [Bug] Events page duplicated events
### Description of the Bug

The events pages sometimes shows duplicated events.

### Reproduction Steps

Go to events page.

### Expected Behaviour

Events shouldn't be duplicated,

### OS

macOS

### Browser

_No response_

### Device

_No response_

### Additional Notes

Image

### PR DESCRIPTION
**Pull request by yl275**
### Description
Refactor the Events component to use local state for EVENTS instead of a module-level array.

### Changes Made
Replaced 
```
const EVENTS: Event[] = [] 
```
with 
```
const [EVENTS, setEVENTS] = useState<Event[]>([])
```

### Related Issues
Fixes #295 

### Additional Notes
N/A

### CODE REVIEW

**Comment by yl275** [comment]
As events are unlikely to be updated frequently, I think we don’t need a hardcoded refresh interval.

File: src/app/events/Events.tsx [hunk 1]
```diff
@@ -25,16 +22,9 @@ function Title({ children }: { children: string }) {
...
 export default function Events({ className }: { className?: string }) {
-    const [loading, setLoading] = useState(true);
-
-    useMount(() => {
-        fetchEvents().then((events) => {
-            EVENTS.push(...events);
-            setLoading(false);
-        });
-    });
+    const { data: EVENTS, error, isLoading } = useSWR('events', fetchEvents);
```
Comment (phoenixpereira) [inline src/app/events/Events.tsx:25]: Remove unused `error` const.

**Review by phoenixpereira — CHANGES_REQUESTED** [review]
