### PR TITLE
fix: add existing email error popup

### LINKED ISSUE #149: [Bug] Signing up with an account that already exists doesn’t show the error in the UI.
### Description of the Bug

Signing up with an account that already exists doesn’t show the error in the UI.

### Reproduction Steps

- Create an account.
- Sign out.
- Try to create and account with the same email address.

### Expected Behaviour

Should show an error message in the sign up bx like "Account already exists, please sign in instead."

### OS

macOS

### Browser

_No response_

### Device

_No response_

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by Techngo10**
Description
Added Error message for existing email used

Changes Made
Added line 133 - 136

Related Issues
[Bug] Signing up with an account that already exists doesn’t show the error in the UI. Fixes #149 

Additional Info
Changed step one line 135, as it had unnecessary white space, and it wasn't pretty enough

### CODE REVIEW

**Comment by phoenixpereira** [comment]
@Techngo10 To test it, you would need to make a Clerk account and make an account with an email address and then try making a new account with the same email address. See https://github.com/compsci-adl/website/blob/main/docs/clerk.md.

File: src/app/(account)/join/steps/StepOne.tsx [hunk 1]
```diff
@@ -129,6 +129,11 @@ export default function StepOne() {
                     message:
                         'Password has been found in an online data breach. For account safety, please use a different password.',
                 },
+                {
+                    code: 'form_email_already_exists',
```
Comment (phoenixpereira) [inline src/app/(account)/join/steps/StepOne.tsx:133]: Code should be `form_identifier_exists`.

**Review by phoenixpereira — CHANGES_REQUESTED** [review]

**Review by rayokamoto — APPROVED** [review]

**Review by phoenixpereira — APPROVED** [review]
